### ISSUE TITLE
[Feat] 심볼 Bottom Sheets UI

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#17]
## Issue

심볼 Bottom Sheets UI를 만듭니다.

## To-do

- [x] cardImageView 터치 이벤트 등록
- [x] 심볼 Bottom Sheets
- [x] 심볼 에셋 위치시키기
- [x] 이미지 업로드 버튼
