### ISSUE TITLE
[Feat] 카드나/카드너 작성 완료 뷰 AutoLayout

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#218]
## Issue

카드나/카드너 작성 완료 뷰 AutoLayout 설정

## To-do

- [ ] 카드나 작성 완료 뷰 AutoLayout
- [ ] 로티를 완성 카드 뒤에 두기
- [ ] 카드너(타인 소개 작성) 작성 완료 뷰 AutoLayout
