### ISSUE TITLE
[Fix] 타인소개 작성 텍스트필드 border 제거

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#235]
## Issue

타인소개 작성 텍스트필드 border 제거
(모든 textfield에 대한 border style을 `.none`으로 두고 textfield의 height값을 지정합니다.

## To-do

- [ ] 타인소개 작성 텍스트필드 border style `.none`
- [ ] 회원가입 email, password border style `.none`
- [ ] 회원가입 이름 border style `.none`
