### ISSUE TITLE
[Docs] 중간과제를 위한 Readme 수정

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#3]
## Issue

중간과제를 위한 Readme.md 파일 수정

## To-do

- [x] 간단한 프로젝트 설명
- [x] 참여 구성원
- [x] Coding Convention
- [x] Git branch 전략
- [x] 프로젝트 폴더링 Convention
- [x] 그 밖의 디지게 이쁜 꾸밈 요소
