### ISSUE TITLE
[Fix] 대표카드 뷰 버그 픽스

### ISSUE THREAD

**Issue by hyesuuou** [TeamCARDNA/Cardna-iOS#362]
## Issue

대표카드 뷰의 자잘한 버그들을 고칩니다

## To-do

- [x] 상단 메시지에 ! 붙이기
- [ ] 하단 인덱스 오류 수정
- [ ] 인덱스 색상 수정
