### ISSUE TITLE
[Feat] 카드나/카드너 작성 뷰 리메이킹 작업

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#391]
## Issue

기존에 코드베이스(SnapKit + Then)로 만들었던 카드나/카드너 작성 뷰를 스토리보드 기반으로 리메이킹하는 작업을 수행합니다.

## To-do

- [x] 헤더 UI
- [x] 사진/심볼 이미지 UI
- [x] 카드 제목 UI
- [x] 카드 본문 UI
