### ISSUE TITLE
[Fix] 세세한 이슈 수정목록

### ISSUE THREAD

**Issue by hyesuuou** [TeamCARDNA/Cardna-iOS#464]
## To-do

- [x] 마이페이지 이름 변경된거 수정하기
- [x] 카드너 보관함 엠티뷰 랜덤코드 + 복사
- [x] 탭바 마이페이지 아이콘 변경사항 수정
- [x] 친구 대표카드 하단바 보이게 바꾸기
