### ISSUE TITLE
[Feat] 카드나/카드너 뷰컨 재사용해서 분기처리하기

### ISSUE THREAD

**Issue by ningpop** [TeamCARDNA/Cardna-iOS#90]
## Issue

카드나/카드너 ViewController를 재사용하여 분기처리 작업이 있습니다.

## To-do

- [x] 카드나/카드너 ViewController를 재사용하게 만들기
- [x] 카드너에서 버튼 색상 변경 분기처리
- [x] 카드너에서 대상 지정 뷰 만들고 연결
- [x] 타인과의 관계 textField 데이터 전달
- [x] 심볼 선택 기능
- [x] 심볼 선택 시 기본 카드 이미지 설정
